// generated by scripts/gen_component.js

include ReactNative.ImageBackground

module Compat = ReactNative.ImageBackground

@react.component @module("react-native")
external make: (
  ~ref: ref=?,
  // ImageBackground props
  ~imageRef: Image.ref=?,
  ~imageStyle: Style2.t<[< Style2.imageStyle]>=?,
  // Image props
  ~accessibilityLabel: string=?,
  ~accessible: bool=?,
  ~blurRadius: float=?,
  ~capInsets: View.edgeInsets=?,
  ~defaultSource: Image.DefaultSource.t=?,
  ~fadeDuration: float=?,
  ~loadingIndicatorSource: array<Image.Source.t>=?,
  ~onError: Image.errorEvent => unit=?,
  ~onLayout: Event.layoutEvent => unit=?,
  ~onLoad: unit => unit=?,
  ~onLoadEnd: unit => unit=?,
  ~onLoadStart: unit => unit=?,
  ~onPartialLoad: unit => unit=?,
  ~onProgress: Image.progressEvent => unit=?,
  ~progressiveRenderingEnabled: bool=?,
  ~resizeMethod: Image.resizeMethod=?,
  ~resizeMode: Style.resizeMode=?,
  ~source: Image.Source.t,
  ~style: Style2.t<[< Style2.viewStyle]>=?,
  ~testID: string=?,
  ~children: React.element=?,
) => React.element = "ImageBackground"

