// generated by scripts/gen_component.js

include ReactNative.InputAccessoryView

module Compat = ReactNative.InputAccessoryView

@react.component @module("react-native")
external make: (
  ~backgroundColor: Color.t=?,
  ~nativeID: string=?,
  ~style: Style2.t<[< Style2.viewStyle]>=?,
  ~testID: string=?,
  ~children: React.element=?,
) => React.element = "InputAccessoryView"

