(** This file is partially generated by genStyles.ts *)

include Style2_basis.Sig

(* types *)

type flexStyle =
  [ `alignContent
  | `alignItems
  | `alignSelf
  | `aspectRatio
  | `borderBottomWidth
  | `borderEndWidth
  | `borderLeftWidth
  | `borderRightWidth
  | `borderStartWidth
  | `borderTopWidth
  | `borderWidth
  | `bottom
  | `display
  | `_end (* Renamed to be compatible with rescript-react-native *)
  | `flex
  | `flexBasis
  | `flexDirection
  | `flexGrow
  | `flexShrink
  | `flexWrap
  | `height
  | `justifyContent
  | `left
  | `margin
  | `marginBottom
  | `marginEnd
  | `marginHorizontal
  | `marginLeft
  | `marginRight
  | `marginStart
  | `marginTop
  | `marginVertical
  | `maxHeight
  | `maxWidth
  | `minHeight
  | `minWidth
  | `overflow
  | `padding
  | `paddingBottom
  | `paddingEnd
  | `paddingHorizontal
  | `paddingLeft
  | `paddingRight
  | `paddingStart
  | `paddingTop
  | `paddingVertical
  | `position
  | `right
  | `start
  | `top
  | `width
  | `zIndex
  | `direction ]

type transformsStyle =
  [ `transform
  | `transformMatrix
  | `rotation
  | `scaleX
  | `scaleY
  | `translateX
  | `translateY ]

type shadowStyleIOS =
  [ `shadowColor | `shadowOffset | `shadowOpacity | `shadowRadius ]

type viewStyle =
  [ flexStyle
  | shadowStyleIOS
  | transformsStyle
  | `backfaceVisibility
  | `backgroundColor
  | `borderBottomColor
  | `borderBottomEndRadius
  | `borderBottomLeftRadius
  | `borderBottomRightRadius
  | `borderBottomStartRadius
  | `borderBottomWidth
  | `borderColor
  | `borderEndColor
  | `borderLeftColor
  | `borderLeftWidth
  | `borderRadius
  | `borderRightColor
  | `borderRightWidth
  | `borderStartColor
  | `borderStyle
  | `borderTopColor
  | `borderTopEndRadius
  | `borderTopLeftRadius
  | `borderTopRightRadius
  | `borderTopStartRadius
  | `borderTopWidth
  | `borderWidth
  | `opacity
  | `testID
  | `elevation ]

type textStyleIOS =
  [ viewStyle
  | `fontVariant
  | `letterSpacing
  | `textDecorationColor
  | `textDecorationStyle
  | `writingDirection ]

type textStyleAndroid = [ viewStyle | `textAlignVertical | `includeFontPadding ]

type textStyle =
  [ textStyleIOS
  | textStyleAndroid
  | viewStyle
  | `color
  | `fontFamily
  | `fontSize
  | `fontStyle
  | `fontWeight
  | `letterSpacing
  | `lineHeight
  | `textAlign
  | `textDecorationLine
  | `textDecorationStyle
  | `textDecorationColor
  | `textShadowColor
  | `textShadowOffset
  | `textShadowRadius
  | `textTransform
  | `testID ]

type imageStyle =
  [ flexStyle
  | shadowStyleIOS
  | transformsStyle
  | `resizeMode
  | `backfaceVisibility
  | `borderBottomLeftRadius
  | `borderBottomRightRadius
  | `backgroundColor
  | `borderColor
  | `borderWidth
  | `borderRadius
  | `borderTopLeftRadius
  | `borderTopRightRadius
  | `overflow
  | `overlayColor
  | `tintColor
  | `opacity ]

(* externals *)
external flexStyle : [< flexStyle ] style -> ReactNative.Style.t
  = "%identity"

external transformsStyle :
  [< transformsStyle ] style -> ReactNative.Style.t = "%identity"

external shadowStyleIOS :
  [< shadowStyleIOS ] style -> ReactNative.Style.t = "%identity"

external viewStyle : [< viewStyle ] style -> ReactNative.Style.t
  = "%identity"

external textStyleIOS :
  [< textStyleIOS ] style -> ReactNative.Style.t = "%identity"

external textStyleAndroid :
  [< textStyleAndroid ] style -> ReactNative.Style.t = "%identity"

external textStyle : [< textStyle ] style -> ReactNative.Style.t
  = "%identity"

external imageStyle : [< imageStyle ] style -> ReactNative.Style.t
  = "%identity"

(* accessors *)
val alignContent :
  [ `flexStart | `flexEnd | `center | `stretch | `spaceBetween | `spaceAround ] ->
  [> `alignContent ] style_prop

val alignItems :
  [ `flexStart | `flexEnd | `center | `stretch | `baseline ] ->
  [> `alignItems ] style_prop

val alignSelf :
  [ `flexStart | `flexEnd | `center | `stretch | `baseline | `auto ] ->
  [> `alignSelf ] style_prop

val aspectRatio : float -> [> `aspectRatio ] style_prop

val borderBottomWidth : float -> [> `borderBottomWidth ] style_prop

val borderEndWidth : ReactNative.Style.size -> [> `borderEndWidth ] style_prop

val borderLeftWidth : float -> [> `borderLeftWidth ] style_prop

val borderRightWidth : float -> [> `borderRightWidth ] style_prop

val borderStartWidth :
  ReactNative.Style.size -> [> `borderStartWidth ] style_prop

val borderTopWidth : float -> [> `borderTopWidth ] style_prop

val borderWidth : float -> [> `borderWidth ] style_prop

val bottom : ReactNative.Style.size -> [> `bottom ] style_prop

val display : ReactNative.Style.display -> [> `display ] style_prop

val end_ : ReactNative.Style.size -> [> `_end ] style_prop

val flex : float -> [> `flex ] style_prop

val flexBasis : ReactNative.Style.size -> [> `flexBasis ] style_prop

val flexDirection :
  [ `row | `column | `rowReverse | `columnReverse ] ->
  [> `flexDirection ] style_prop

val flexGrow : float -> [> `flexGrow ] style_prop

val flexShrink : float -> [> `flexShrink ] style_prop

val flexWrap : ReactNative.Style.flexWrap -> [> `flexWrap ] style_prop

val height : ReactNative.Style.size -> [> `height ] style_prop

val justifyContent :
  [ `flexStart
  | `flexEnd
  | `center
  | `spaceBetween
  | `spaceAround
  | `spaceEvenly ] ->
  [> `justifyContent ] style_prop

val left : ReactNative.Style.size -> [> `left ] style_prop

val margin : ReactNative.Style.margin -> [> `margin ] style_prop

val marginBottom : ReactNative.Style.margin -> [> `marginBottom ] style_prop

val marginEnd : ReactNative.Style.margin -> [> `marginEnd ] style_prop

val marginHorizontal :
  ReactNative.Style.margin -> [> `marginHorizontal ] style_prop

val marginLeft : ReactNative.Style.margin -> [> `marginLeft ] style_prop

val marginRight : ReactNative.Style.margin -> [> `marginRight ] style_prop

val marginStart : ReactNative.Style.margin -> [> `marginStart ] style_prop

val marginTop : ReactNative.Style.margin -> [> `marginTop ] style_prop

val marginVertical : ReactNative.Style.margin -> [> `marginVertical ] style_prop

val maxHeight : ReactNative.Style.size -> [> `maxHeight ] style_prop

val maxWidth : ReactNative.Style.size -> [> `maxWidth ] style_prop

val minHeight : ReactNative.Style.size -> [> `minHeight ] style_prop

val minWidth : ReactNative.Style.size -> [> `minWidth ] style_prop

val overflow : ReactNative.Style.overflow -> [> `overflow ] style_prop

val padding : ReactNative.Style.size -> [> `padding ] style_prop

val paddingBottom : ReactNative.Style.size -> [> `paddingBottom ] style_prop

val paddingEnd : ReactNative.Style.size -> [> `paddingEnd ] style_prop

val paddingHorizontal :
  ReactNative.Style.size -> [> `paddingHorizontal ] style_prop

val paddingLeft : ReactNative.Style.size -> [> `paddingLeft ] style_prop

val paddingRight : ReactNative.Style.size -> [> `paddingRight ] style_prop

val paddingStart : ReactNative.Style.size -> [> `paddingStart ] style_prop

val paddingTop : ReactNative.Style.size -> [> `paddingTop ] style_prop

val paddingVertical : ReactNative.Style.size -> [> `paddingVertical ] style_prop

val position : ReactNative.Style.position -> [> `position ] style_prop

val right : ReactNative.Style.size -> [> `right ] style_prop

val start : ReactNative.Style.size -> [> `start ] style_prop

val top : ReactNative.Style.size -> [> `top ] style_prop

val width : ReactNative.Style.size -> [> `width ] style_prop

val zIndex : float -> [> `zIndex ] style_prop

val direction : [ `inherit_ | `ltr | `rtl ] -> [> `direction ] style_prop

val transform : ReactNative.Style.transform array -> [> `transform ] style_prop

val transformMatrix : float array -> [> `transformMatrix ] style_prop

val rotation : float -> [> `rotation ] style_prop

val scaleX : float -> [> `scaleX ] style_prop

val scaleY : float -> [> `scaleY ] style_prop

val translateX : float -> [> `translateX ] style_prop

val translateY : float -> [> `translateY ] style_prop

val fontVariant :
  ReactNative.FontVariant.t array -> [> `fontVariant ] style_prop

val letterSpacing : float -> [> `letterSpacing ] style_prop

val textDecorationColor :
  ReactNative.Color.t -> [> `textDecorationColor ] style_prop

val textDecorationStyle :
  ReactNative.Style.textDecorationStyle -> [> `textDecorationStyle ] style_prop

val writingDirection :
  ReactNative.Style.writingDirection -> [> `writingDirection ] style_prop

val textAlignVertical :
  ReactNative.Style.textAlignVertical -> [> `textAlignVertical ] style_prop

val includeFontPadding : bool -> [> `includeFontPadding ] style_prop

val color : ReactNative.Color.t -> [> `color ] style_prop

val fontFamily : string -> [> `fontFamily ] style_prop

val fontSize : float -> [> `fontSize ] style_prop

val fontStyle : ReactNative.Style.fontStyle -> [> `fontStyle ] style_prop

val fontWeight :
  [ `normal
  | `bold
  | `_100
  | `_200
  | `_300
  | `_400
  | `_500
  | `_600
  | `_700
  | `_800
  | `_900 ] ->
  [> `fontWeight ] style_prop

val lineHeight : float -> [> `lineHeight ] style_prop

val textAlign : ReactNative.Style.textAlign -> [> `textAlign ] style_prop

val textDecorationLine :
  [ `none | `underline | `lineThrough | `underlineLineThrough ] ->
  [> `textDecorationLine ] style_prop

val textShadowColor : ReactNative.Color.t -> [> `textShadowColor ] style_prop

val textShadowOffset :
  ReactNative.Style.offset -> [> `textShadowOffset ] style_prop

val textShadowRadius : float -> [> `textShadowRadius ] style_prop

val textTransform :
  ReactNative.Style.textTransform -> [> `textTransform ] style_prop

val testID : string -> [> `testID ] style_prop

val backfaceVisibility :
  ReactNative.Style.backfaceVisibility -> [> `backfaceVisibility ] style_prop

val backgroundColor : ReactNative.Color.t -> [> `backgroundColor ] style_prop

val borderBottomColor :
  ReactNative.Color.t -> [> `borderBottomColor ] style_prop

val borderBottomEndRadius : float -> [> `borderBottomEndRadius ] style_prop

val borderBottomLeftRadius : float -> [> `borderBottomLeftRadius ] style_prop

val borderBottomRightRadius : float -> [> `borderBottomRightRadius ] style_prop

val borderBottomStartRadius : float -> [> `borderBottomStartRadius ] style_prop

val borderColor : ReactNative.Color.t -> [> `borderColor ] style_prop

val borderEndColor : ReactNative.Color.t -> [> `borderEndColor ] style_prop

val borderLeftColor : ReactNative.Color.t -> [> `borderLeftColor ] style_prop

val borderRadius : float -> [> `borderRadius ] style_prop

val borderRightColor : ReactNative.Color.t -> [> `borderRightColor ] style_prop

val borderStartColor : ReactNative.Color.t -> [> `borderStartColor ] style_prop

val borderStyle : ReactNative.Style.borderStyle -> [> `borderStyle ] style_prop

val borderTopColor : ReactNative.Color.t -> [> `borderTopColor ] style_prop

val borderTopEndRadius : float -> [> `borderTopEndRadius ] style_prop

val borderTopLeftRadius : float -> [> `borderTopLeftRadius ] style_prop

val borderTopRightRadius : float -> [> `borderTopRightRadius ] style_prop

val borderTopStartRadius : float -> [> `borderTopStartRadius ] style_prop

val opacity : float -> [> `opacity ] style_prop

val elevation : float -> [> `elevation ] style_prop

val shadowColor : ReactNative.Color.t -> [> `shadowColor ] style_prop

val shadowOffset : ReactNative.Style.offset -> [> `shadowOffset ] style_prop

val shadowOpacity : float -> [> `shadowOpacity ] style_prop

val shadowRadius : float -> [> `shadowRadius ] style_prop

val resizeMode : ReactNative.Style.resizeMode -> [> `resizeMode ] style_prop

val overlayColor : ReactNative.Color.t -> [> `overlayColor ] style_prop

val tintColor : ReactNative.Color.t -> [> `tintColor ] style_prop
